# This is the default configuration file for the Kattis CLI.
# Use TOML format https://toml.io/en/
# Just copy the default section and modify the values according the language

title = "Kattis-cli language configuration file for local testing."

[default]
compile = "" # no compile command for this language
execute = "python3 {mainfile}" # the command to run the program
mainfile = "{problemid}.py" # the name of the main file or file with mainclass

[python3]
compile = ""
execute = "python3 {mainfile}"
mainfile = "{problemid}.py"

[cpp]
compile = "g++ -g -O2 -std=gnu++23 -static -lrt -Wl,--whole-archive -lpthread -Wl,--no-whole-archive"
execute = "./a.out"
mainfile = "{problemid}.cpp"

[c]
compile = "gcc -g -O2 -std=gnu23 -static -lm"
execute = "./a.out"
mainfile = "{problemid}.c"

[nodejs]
compile = "node -c"
execute = "node {mainfile}"
mainfile = "{problemid}.js"

[java]
compile = "javac -d ."
execute = "java -cp . {mainfile}"
mainfile = "{problemid}"
